name       : python-asgiref
version    : 3.5.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/a/asgiref/asgiref-3.5.2.tar.gz : 4a29362a6acebe09bf1d6640db38c1dc3d9217c68e6f9f6204d72667fc19a424
homepage   : https://github.com/django/asgiref/
license    : BSD-3-Clause
component  : programming.python
summary    : ASGI specs, helper code, and adapters
description: |
    ASGI is a standard for Python asynchronous web apps and servers to communicate with each other, and positioned as an asynchronous successor to WSGI.
builddeps  :
    - python-pytest-asyncio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
