name       : python-asgiref
version    : 3.7.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/a/asgiref/asgiref-3.7.2.tar.gz : 9e0ce3aa93a819ba5b45120216b23878cf6e8525eb3848653452b4192b92afed
homepage   : https://github.com/django/asgiref/
license    : BSD-3-Clause
component  : programming.python
summary    : ASGI specs, helper code, and adapters
description: |
    ASGI is a standard for Python asynchronous web apps and servers to communicate with each other, and positioned as an asynchronous successor to WSGI.
builddeps  :
    - python-pytest-asyncio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
